### ISSUE TITLE
design member table

### ISSUE THREAD

**Issue by SavePlanetDev** [SavePlanetDev/360-back#2]
ตอนแรกจะออกแบบให้มีแต่ member table อย่างเดียว แต่เปรมบอกว่า จะต้องแยก table ออกเป็น 2 table ก็คือ table ที่เป็นข้อมูลที่ไม่ใช่ wallet กับ ข้อมูลที่เป็น wallet ก็จะได้ 2 table

1. member table : เก็บข้อมูล member + setting
2. wallet table : เก็บข้อมูล wallet addresses ของ member ( 1 member : N wallet | N <=3)

![Image](https://user-images.githubusercontent.com/22347555/214998757-e5f677c4-8397-4504-9584-170763749db8.png)

diagram-link: https://app.diagrams.net/#G1nO43lJK6JAX2w6dAOz2zpRg_hCPaievK

**Comment by mojisejr** [comment]
ได้ครับผมลืมเอาออก ถถถถถถถ @parametprame

**Comment by mojisejr** [comment]
เป็นแบบนี้เนาะ ผมเปลี่ยนให้แล้ว
![Image](https://user-images.githubusercontent.com/22347555/215002420-edb24f2d-6dc0-4668-a694-6a46344571ac.png)
